[2024-09-21 12:36:58,957] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: scrapy_spiders_dag.run_massae_spark_job manual__2024-09-21T12:36:53.414802+00:00 [queued]>
[2024-09-21 12:36:58,973] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: scrapy_spiders_dag.run_massae_spark_job manual__2024-09-21T12:36:53.414802+00:00 [queued]>
[2024-09-21 12:36:58,973] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2024-09-21 12:36:58,973] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2024-09-21 12:36:58,974] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2024-09-21 12:36:58,990] {taskinstance.py:1378} INFO - Executing <Task(SparkSubmitOperator): run_massae_spark_job> on 2024-09-21 12:36:53.414802+00:00
[2024-09-21 12:36:58,998] {standard_task_runner.py:52} INFO - Started process 134 to run task
[2024-09-21 12:36:59,002] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'scrapy_spiders_dag', 'run_massae_spark_job', 'manual__2024-09-21T12:36:53.414802+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/stream.py', '--cfg-path', '/tmp/tmpycl3z6iy', '--error-file', '/tmp/tmpzk6e7b4w']
[2024-09-21 12:36:59,002] {standard_task_runner.py:80} INFO - Job 142: Subtask run_massae_spark_job
[2024-09-21 12:36:59,069] {task_command.py:370} INFO - Running <TaskInstance: scrapy_spiders_dag.run_massae_spark_job manual__2024-09-21T12:36:53.414802+00:00 [running]> on host 6cc6c21077c9
[2024-09-21 12:36:59,169] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrapy_spiders_dag
AIRFLOW_CTX_TASK_ID=run_massae_spark_job
AIRFLOW_CTX_EXECUTION_DATE=2024-09-21T12:36:53.414802+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-21T12:36:53.414802+00:00
[2024-09-21 12:36:59,181] {spark_submit.py:218} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-09-21 12:36:59,182] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --packages org.apache.hadoop:hadoop-aws:3.2.0 --name arrow-spark /opt/spark-scripts/massae_spark_script.py
[2024-09-21 12:36:59,409] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2024-09-21 12:36:59,413] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2024-09-21 12:36:59,459] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages org.apache.hadoop:hadoop-aws:3.2.0 --name arrow-spark /opt/spark-scripts/massae_spark_script.py. Error code is: 1.
[2024-09-21 12:36:59,464] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=scrapy_spiders_dag, task_id=run_massae_spark_job, execution_date=20240921T123653, start_date=20240921T123658, end_date=20240921T123659
[2024-09-21 12:36:59,483] {standard_task_runner.py:97} ERROR - Failed to execute job 142 for task run_massae_spark_job (Cannot execute: spark-submit --master yarn --packages org.apache.hadoop:hadoop-aws:3.2.0 --name arrow-spark /opt/spark-scripts/massae_spark_script.py. Error code is: 1.; 134)
[2024-09-21 12:36:59,503] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-21 12:36:59,550] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
