[2024-09-21 12:05:02,377] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: scrapy_spiders_dag.run_massae_spark_job scheduled__2024-09-21T11:04:51.326705+00:00 [queued]>
[2024-09-21 12:05:02,437] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: scrapy_spiders_dag.run_massae_spark_job scheduled__2024-09-21T11:04:51.326705+00:00 [queued]>
[2024-09-21 12:05:02,438] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2024-09-21 12:05:02,439] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2024-09-21 12:05:02,439] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2024-09-21 12:05:02,486] {taskinstance.py:1378} INFO - Executing <Task(SparkSubmitOperator): run_massae_spark_job> on 2024-09-21 11:04:51.326705+00:00
[2024-09-21 12:05:02,507] {standard_task_runner.py:52} INFO - Started process 81 to run task
[2024-09-21 12:05:02,521] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'scrapy_spiders_dag', 'run_massae_spark_job', 'scheduled__2024-09-21T11:04:51.326705+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/stream.py', '--cfg-path', '/tmp/tmpy8n3nzia', '--error-file', '/tmp/tmphs9xynob']
[2024-09-21 12:05:02,522] {standard_task_runner.py:80} INFO - Job 118: Subtask run_massae_spark_job
[2024-09-21 12:05:02,742] {task_command.py:370} INFO - Running <TaskInstance: scrapy_spiders_dag.run_massae_spark_job scheduled__2024-09-21T11:04:51.326705+00:00 [running]> on host a7ef1227d295
[2024-09-21 12:05:03,398] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrapy_spiders_dag
AIRFLOW_CTX_TASK_ID=run_massae_spark_job
AIRFLOW_CTX_EXECUTION_DATE=2024-09-21T11:04:51.326705+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-21T11:04:51.326705+00:00
[2024-09-21 12:05:03,499] {spark_submit.py:218} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-09-21 12:05:03,502] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --packages org.apache.hadoop:hadoop-aws:3.2.0 --name arrow-spark src/massae_spark_script.py
[2024-09-21 12:05:04,095] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-09-21 12:05:04,103] {spark_submit.py:490} INFO - JAVA_HOME is not set
[2024-09-21 12:05:04,158] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages org.apache.hadoop:hadoop-aws:3.2.0 --name arrow-spark src/massae_spark_script.py. Error code is: 1.
[2024-09-21 12:05:04,175] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=scrapy_spiders_dag, task_id=run_massae_spark_job, execution_date=20240921T110451, start_date=20240921T120502, end_date=20240921T120504
[2024-09-21 12:05:04,260] {standard_task_runner.py:97} ERROR - Failed to execute job 118 for task run_massae_spark_job (Cannot execute: spark-submit --master yarn --packages org.apache.hadoop:hadoop-aws:3.2.0 --name arrow-spark src/massae_spark_script.py. Error code is: 1.; 81)
[2024-09-21 12:05:04,347] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-21 12:05:04,479] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
