[2024-09-21 12:22:08,075] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: scrapy_spiders_dag.run_massae_spark_job manual__2024-09-21T12:22:02.268129+00:00 [queued]>
[2024-09-21 12:22:08,085] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: scrapy_spiders_dag.run_massae_spark_job manual__2024-09-21T12:22:02.268129+00:00 [queued]>
[2024-09-21 12:22:08,086] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2024-09-21 12:22:08,086] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2024-09-21 12:22:08,086] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2024-09-21 12:22:08,097] {taskinstance.py:1378} INFO - Executing <Task(SparkSubmitOperator): run_massae_spark_job> on 2024-09-21 12:22:02.268129+00:00
[2024-09-21 12:22:08,103] {standard_task_runner.py:52} INFO - Started process 105 to run task
[2024-09-21 12:22:08,107] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'scrapy_spiders_dag', 'run_massae_spark_job', 'manual__2024-09-21T12:22:02.268129+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/stream.py', '--cfg-path', '/tmp/tmpjc8gmdh6', '--error-file', '/tmp/tmpqsnhkn_i']
[2024-09-21 12:22:08,108] {standard_task_runner.py:80} INFO - Job 135: Subtask run_massae_spark_job
[2024-09-21 12:22:08,157] {task_command.py:370} INFO - Running <TaskInstance: scrapy_spiders_dag.run_massae_spark_job manual__2024-09-21T12:22:02.268129+00:00 [running]> on host bb4f2096ef21
[2024-09-21 12:22:08,230] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=scrapy_spiders_dag
AIRFLOW_CTX_TASK_ID=run_massae_spark_job
AIRFLOW_CTX_EXECUTION_DATE=2024-09-21T12:22:02.268129+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-21T12:22:02.268129+00:00
[2024-09-21 12:22:08,240] {spark_submit.py:218} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-09-21 12:22:08,240] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --packages org.apache.hadoop:hadoop-aws:3.2.0 --name arrow-spark /opt/spark-scripts/massae_spark_script.py
[2024-09-21 12:22:08,363] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-09-21 12:22:08,367] {spark_submit.py:490} INFO - JAVA_HOME is not set
[2024-09-21 12:22:08,387] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages org.apache.hadoop:hadoop-aws:3.2.0 --name arrow-spark /opt/spark-scripts/massae_spark_script.py. Error code is: 1.
[2024-09-21 12:22:08,390] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=scrapy_spiders_dag, task_id=run_massae_spark_job, execution_date=20240921T122202, start_date=20240921T122208, end_date=20240921T122208
[2024-09-21 12:22:08,404] {standard_task_runner.py:97} ERROR - Failed to execute job 135 for task run_massae_spark_job (Cannot execute: spark-submit --master yarn --packages org.apache.hadoop:hadoop-aws:3.2.0 --name arrow-spark /opt/spark-scripts/massae_spark_script.py. Error code is: 1.; 105)
[2024-09-21 12:22:08,440] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-21 12:22:08,485] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
